import React from "react";
import {AbsoluteFill, Audio, Composition, Img, interpolate, Sequence, staticFile, useCurrentFrame} from "remotion";

const ORANGE="#f4773b", INK="#171719", CREAM="#f3eee6", GREEN="#6ba889";

const Fade:React.FC<React.PropsWithChildren<{duration:number}>>=({children,duration})=>{const f=useCurrentFrame();const opacity=interpolate(f,[0,24,duration-24,duration],[0,1,1,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <AbsoluteFill style={{opacity}}>{children}</AbsoluteFill>};
const Header:React.FC<{step:string}>=({step})=><div style={{position:"absolute",top:46,left:72,right:72,display:"flex",justifyContent:"space-between",alignItems:"center",zIndex:10}}><div style={{display:"flex",alignItems:"center",gap:16,fontWeight:900,letterSpacing:4,fontSize:24}}><span style={{border:`2px solid currentColor`,borderRadius:10,padding:"7px 11px"}}>V</span> THE VERIFIER</div><div style={{fontSize:22,fontWeight:800,letterSpacing:3}}>{step}</div></div>;
const Caption:React.FC<{text:string}>=({text})=><div style={{position:"absolute",bottom:42,left:"50%",transform:"translateX(-50%)",maxWidth:1500,padding:"16px 28px",borderRadius:18,background:"rgba(23,23,25,.92)",color:"white",fontSize:31,fontWeight:700,lineHeight:1.2,textAlign:"center",zIndex:20}}>{text}</div>;
const Title:React.FC<{kicker:string;title:string;body:string;dark?:boolean}>=({kicker,title,body,dark})=>{const f=useCurrentFrame();const y=interpolate(f,[0,28],[35,0],{extrapolateRight:"clamp"});return <div style={{transform:`translateY(${y}px)`,maxWidth:1080}}><div style={{fontSize:24,fontWeight:900,letterSpacing:5,marginBottom:22,color:dark?ORANGE:INK}}>{kicker}</div><div style={{fontFamily:"Georgia,serif",fontSize:84,lineHeight:.98,letterSpacing:-3,fontWeight:700}}>{title}</div><div style={{fontSize:35,lineHeight:1.26,marginTop:25,maxWidth:930,opacity:.82}}>{body}</div></div>};

const Landing:React.FC<{duration:number}>=({duration})=>{const f=useCurrentFrame();const scale=interpolate(f,[0,duration],[1.08,1],{extrapolateRight:"clamp"});return <Fade duration={duration}><AbsoluteFill style={{background:ORANGE,overflow:"hidden"}}><Img src={staticFile("landing.png")} style={{width:"100%",height:"100%",objectFit:"cover",transform:`scale(${scale})`}}/><Caption text="A confident answer can still be built on outdated evidence."/></AbsoluteFill></Fade>};
const Brief:React.FC<{duration:number}>=({duration})=>{const f=useCurrentFrame();const claim="Verify that Brian Niccol is CEO of Starbucks.";const typed=claim.slice(0,Math.min(claim.length,Math.floor(Math.max(0,f-70)/3)));return <Fade duration={duration}><AbsoluteFill style={{background:CREAM,color:INK,padding:"145px 80px 100px"}}><Header step="01 / 06"/><Title kicker="SPOKEN OR TYPED BRIEF" title="Start with one clear claim." body="Type it—or speak naturally and keep the same conversational context."/><div style={{position:"absolute",left:80,right:80,bottom:150,background:"white",border:`3px solid ${INK}`,borderRadius:28,padding:"30px 36px",boxShadow:`14px 14px 0 ${INK}`,fontSize:38,fontWeight:750}}>{typed}{Math.floor(f/14)%2===0?"|":""}<span style={{float:"right",background:INK,color:"white",padding:"14px 24px",borderRadius:16,fontSize:25}}>● Listening</span></div><Caption text="“Verify that Brian Niccol is the chief executive officer of Starbucks.”"/></AbsoluteFill></Fade>};

const Research:React.FC<{duration:number}>=({duration})=>{const f=useCurrentFrame();const card=(left:boolean)=>{const d=left?50:150,x=interpolate(f,[d,d+35],[left?-120:120,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <div style={{transform:`translateX(${x}px)`,opacity:interpolate(f,[d,d+30],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}),background:left?"#dbeee5":"#ffe0d4",border:`3px solid ${INK}`,borderRadius:28,padding:34,flex:1,minHeight:400,boxShadow:`10px 10px 0 ${INK}`}}><div style={{fontSize:22,fontWeight:900,letterSpacing:4}}>{left?"SUPPORT ANGLE":"CHALLENGE ANGLE"}</div><h3 style={{fontFamily:"Georgia,serif",fontSize:50,lineHeight:1.05,margin:"28px 0 16px"}}>{left?"Brian Niccol is chairman and CEO.":"Laxman Narasimhan was named CEO."}</h3><p style={{fontSize:27,lineHeight:1.35}}>{left?"Starbucks leadership page · Current":"Starbucks announcement · Older"}</p><div style={{marginTop:28,fontWeight:900,fontSize:23}}>{left?"✓ SUPPORTS CLAIM":"× PUBLIC CONTRADICTION"}</div></div>};return <Fade duration={duration}><AbsoluteFill style={{background:ORANGE,color:INK,padding:"138px 76px 100px"}}><Header step="02 / 06"/><Title kicker="OPPOSING EVIDENCE LANES" title="Search for support—and contradiction." body="Both lanes stay visible, so a polished answer cannot hide disagreement."/><div style={{display:"flex",gap:42,position:"absolute",left:76,right:76,bottom:130}}>{card(true)}{card(false)}</div><Caption text="Two real public sources. Two apparently conflicting claims."/></AbsoluteFill></Fade>};

const Resolve:React.FC<{duration:number}>=({duration})=>{const f=useCurrentFrame();const rows=[["Current leadership page","dateModified","2026-08-22","2026-08-22T00:00:00Z"],["CEO announcement","datePublished","2023-03-20","2023-03-20T00:00:00Z"]];return <Fade duration={duration}><AbsoluteFill style={{background:INK,color:CREAM,padding:"145px 76px 100px"}}><Header step="03 / 06"/><Title dark kicker="STRUCTURED DATE METADATA" title="The newer evidence wins for a reason you can inspect." body="Raw metadata is preserved, normalized to UTC, and used deterministically."/><div style={{position:"absolute",left:76,right:76,bottom:135,border:`2px solid ${ORANGE}`,borderRadius:28,overflow:"hidden"}}>{rows.map((r,i)=><div key={r[0]} style={{display:"grid",gridTemplateColumns:"1.5fr 1fr 1fr 1.5fr",padding:"25px 30px",fontSize:27,background:i?"#242427":"#302d2a",opacity:interpolate(f,[40+i*55,80+i*55],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})}}>{r.map(x=><div key={x}>{x}</div>)}</div>)}</div><div style={{position:"absolute",right:90,top:180,background:GREEN,color:INK,borderRadius:999,padding:"16px 25px",fontSize:24,fontWeight:900,opacity:interpolate(f,[120,220],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})}}>CURRENT CLAIM SUPPORTED ✓</div><Caption text="The conflict is resolved by dates—not by whichever sentence sounds stronger."/></AbsoluteFill></Fade>};

const Inspect:React.FC<{duration:number}>=({duration})=><Fade duration={duration}><AbsoluteFill style={{background:CREAM,color:INK,padding:"145px 76px 100px"}}><Header step="04 / 06"/><Title kicker="EVIDENCE-GROUNDED CHAT" title="Keep asking without losing context." body="Sources, dates, and resolution remain active throughout the conversation."/><div style={{position:"absolute",right:76,bottom:135,width:740,background:"white",border:`3px solid ${INK}`,borderRadius:28,padding:34,boxShadow:`12px 12px 0 ${ORANGE}`}}><div style={{fontSize:22,fontWeight:900,letterSpacing:3}}>FOLLOW-UP</div><div style={{fontSize:35,fontWeight:750,marginTop:22}}>Why was the older announcement rejected?</div><div style={{marginTop:22,padding:24,borderRadius:18,background:"#f1e9df",fontSize:27,lineHeight:1.35}}>Its publication date predates the current Starbucks leadership evidence.</div></div><Caption text="Inspect the reasoning, open the sources, and continue the investigation."/></AbsoluteFill></Fade>;

const Approval:React.FC<{duration:number}>=({duration})=>{const f=useCurrentFrame(),ok=f>360;return <Fade duration={duration}><AbsoluteFill style={{background:ORANGE,color:INK,padding:"145px 76px 100px"}}><Header step="05 / 06"/><Title kicker="SERVER-ENFORCED APPROVAL" title="Research is not permission to save." body="A one-time token gates persistence. Export stays locked until the server confirms approval."/><div style={{position:"absolute",right:100,top:275,width:650,background:CREAM,border:`3px solid ${INK}`,borderRadius:32,padding:42,boxShadow:`14px 14px 0 ${INK}`,textAlign:"center"}}><div style={{fontSize:76}}>{ok?"✓":"⌁"}</div><div style={{fontFamily:"Georgia,serif",fontSize:46,fontWeight:700}}>{ok?"Dossier saved":"Save this verified brief?"}</div><div style={{fontSize:26,margin:"22px 0 30px"}}>{ok?"Server-confirmed approval received.":"Nothing is persisted until you decide."}</div><div style={{background:ok?GREEN:INK,color:ok?INK:"white",borderRadius:16,padding:20,fontSize:27,fontWeight:900}}>{ok?"EXPORT DOSSIER":"APPROVE & SAVE"}</div></div><Caption text={ok?"Approval confirmed. Persistence and export are now enabled.":"Without explicit approval, the server refuses to save."}/></AbsoluteFill></Fade>};

const Export:React.FC<{duration:number}>=({duration})=><Fade duration={duration}><AbsoluteFill style={{background:CREAM,color:INK,padding:"145px 76px 100px"}}><Header step="06 / 06"/><Title kicker="AUDITABLE OUTPUT" title="A dossier you can actually defend." body="Claim, source URLs, evidence roles, raw dates, normalized dates, resolution, and approval checkpoint."/><div style={{position:"absolute",right:90,bottom:140,display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,width:730}}>{["Original claim","Opposing sources","Date metadata","Resolution logic","Approval proof","Export record"].map((x,i)=><div key={x} style={{background:i===5?INK:"white",color:i===5?"white":INK,border:`2px solid ${INK}`,borderRadius:16,padding:"22px 24px",fontSize:26,fontWeight:850}}>✓ {x}</div>)}</div><Caption text="An inspectable audit trail for decisions that matter."/></AbsoluteFill></Fade>;
const Closing:React.FC<{duration:number}>=({duration})=><Fade duration={duration}><AbsoluteFill style={{background:INK,color:CREAM,alignItems:"center",justifyContent:"center",textAlign:"center"}}><div style={{fontSize:25,fontWeight:900,letterSpacing:6,color:ORANGE}}>THE VERIFIER</div><div style={{fontFamily:"Georgia,serif",fontSize:108,lineHeight:1,letterSpacing:-4,maxWidth:1450,marginTop:35}}>Verify first.<br/>Save only when you are ready.</div><div style={{fontSize:36,marginTop:42,opacity:.78}}>Evidence first. Approval always.</div><div style={{marginTop:50,display:"flex",gap:20}}><span style={{background:ORANGE,color:INK,borderRadius:18,padding:"18px 28px",fontSize:25,fontWeight:900}}>github.com/Reet24-del/the-verifier</span><span style={{border:`2px solid ${ORANGE}`,color:ORANGE,borderRadius:18,padding:"18px 28px",fontSize:25,fontWeight:900}}>BUILT WITH TRUEFORGE</span></div><Caption text="The Verifier gives you the evidence, explains the conflict, and waits for approval."/></AbsoluteFill></Fade>;

const Video:React.FC=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{fontFamily:"Inter,ui-sans-serif,system-ui",background:INK}}><Audio src={staticFile("voiceover.mp3")}/><Sequence durationInFrames={540}><Landing duration={540}/></Sequence><Sequence from={540} durationInFrames={600}><Brief duration={600}/></Sequence><Sequence from={1140} durationInFrames={750}><Research duration={750}/></Sequence><Sequence from={1890} durationInFrames={900}><Resolve duration={900}/></Sequence><Sequence from={2790} durationInFrames={630}><Inspect duration={630}/></Sequence><Sequence from={3420} durationInFrames={780}><Approval duration={780}/></Sequence><Sequence from={4200} durationInFrames={600}><Export duration={600}/></Sequence><Sequence from={4800} durationInFrames={600}><Closing duration={600}/></Sequence><div style={{position:"absolute",left:0,bottom:0,height:8,width:"100%",background:"rgba(255,255,255,.15)"}}><div style={{height:"100%",background:ORANGE,width:`${(f/5400)*100}%`}}/></div></AbsoluteFill>};
export const MyComposition=()=> <Composition id="VerifierDemo" component={Video} durationInFrames={5400} fps={30} width={1920} height={1080}/>;
